# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93c4f5cb8cd7e93eb3268f41a759116aa35a30ac89efed662534e547dfe3ae99375bec6bac260c56db0d08943c93b5fc8e37e6d70056956a902d356c1ae011f1

test:
  secret_key_base: b6e48239c8e18a678ffb5b06174b8d67d487b57be007f857d4899d0a385715c11e093c700eb81a611cb02b4ecf17c6899607979665542160801df845343cad50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
